// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreFrontUK.Services.InventoryService.Data;

#nullable disable

namespace StoreFrontUK.Migrations.ProductDb
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20251007120901_InitialCreate_Products")]
    partial class InitialCreate_Products
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StoreFrontUK.Services.InventoryService.Entities.InventoryItem", b =>
                {
                    b.Property<string>("ProductSku")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("StockLevel")
                        .HasColumnType("int");

                    b.HasKey("ProductSku");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("StoreFrontUK.Services.InventoryService.Entities.Product", b =>
                {
                    b.Property<string>("Sku")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("CanReorder")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Sku");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
